### ISSUE TITLE
关于在Ark工程中使用ArkPlug中的第三方jar包

### ISSUE THREAD

**Issue by liutw123** [alipay/sofa-ark#126]
### Your question

（1）在Ark工程中可以直接使用ArkPlug中没有export的第三方jar包吗？
（2）在ArkPlug中export的第三方jar包，在Ark工程是否可以直接使用？
（3）我们测试下来，在两个ArkPlug中引入了不同版本的第三方jar包，无论是否export的第三方jar包，
         在Ark工程中都只能使用其中一个ArkPlug中的第三方jar包。
    
### Environment
- SOFAArk version:0.5.2

**Comment by Mobel123** [comment]
@liutw123 
我理解是这样
1. 可以的. （其实这个三方包是通过传递依赖传递到ark工程的，此时三方包是通过bizClassLoader加载的）
2. 可以使用 （不过此时这个三方包是通过pluginClassLoader加载的）

3. plugin中的三方包如果没有排除的话，是会通过传递依赖自动引入到ark工程。maven仲裁后就只留下一个了。

@QilongZhang 我的理解对吧？

**Comment by QilongZhang** [comment]
@liutw123 @Mobel123 
+ 在Ark工程中可以直接使用ArkPlug中没有export的第三方jar包吗？
> 使用不了，如果工程自身没有引入对应的依赖，arkplugin也没有导出，是加载不到的，会报ClassNotFound.

+ 在ArkPlug中export的第三方jar包，在Ark工程是否可以直接使用？
> 可以的，为了编译通过，工程需要引入对应的依赖包，但是可以设置 scope 为provide，因为运行时会去arkplugin加载

+ plugin中的三方包如果没有排除的话，是会通过传递依赖自动引入到ark工程。maven仲裁后就只留下一个了。
> 打包插件时，如果你不想一些依赖包传递给应用，可以设置 <optional>true</optional>，不过即使引入到了ark工程，如果你将此依赖包导出，应用仍然会让arkpluing 加载。

**Comment by liutw123** [comment]
@Mobel123 @QilongZhang 
关于（1），我的观点和@Mobel123一样，如果arkplugin的第三方依赖包引入通过传递依赖传递到ark工程，可以被直接使用。

如果我想在Ark工程中直接使用多个arkplugin中不同版本的第三方jar包应该怎么做？

**Comment by QilongZhang** [comment]
嗯，ark plugin间接传递的包在工程的classpath中，肯定是可以使用的。如果你不想传递可以添加
```text
<optional>true<optional>
```
optional 参考 https://stackoverflow.com/questions/20993068/what-are-optional-maven-dependencies

+ 如果我想在Ark工程中直接使用多个arkplugin中不同版本的第三方jar包应该怎么做？
> 在ark工程中不可以同时直接使用第三方包，应该是有一个中间件，参考下面这张图

![image](https://user-images.githubusercontent.com/8833026/45801266-fba18780-bce5-11e8-9341-343505f70805.png)

**Comment by liutw123** [comment]
好的，thx
