### ISSUE TITLE
多个ArkBiz包运行在一个Ark容器中

### ISSUE THREAD

**Issue by lux2018** [alipay/sofa-ark#128]
@QilongZhang 你好，

我看文档中有讲到，通过打包发布的Ark 包，在其他应用可以直接当成 Jar 包依赖，运行在同一个 SOFAArk 容器之上。

我这边打包好了一个Ark Biz包。然后把另一个springboot的应用改成一个Ark工程，如果想在这个Ark工程中使用前面打包好的Ark Biz包，应该怎么做？有没有类似的Demo？

 SOFAArk version:0.5.2

**Comment by QilongZhang** [comment]
@lux2018  没有特殊的操作，当成普通依赖引入进工程就可以了，启动ark工程时，被引入进来的ark biz包也会被启动。

**Comment by lux2018** [comment]
@QilongZhang 是的，不过引入进来的ark biz 和 ark 工程之间服务引用是不是得通过jvm或者rpc来实现？这样的话感觉可以使用jarslink2.0了。

另外，如果我们在普通的jar模块中引用ark plugin,然后将模块打成普通jar包，再在ark工程中引入这个含有ark plugin的普通jar包，这个jar包里边的ark plugin也会被专门的arkplugin classloader加载对吧？我们想在我们的实际项目通过这种方式来解决jar包的冲突问题。

**Comment by QilongZhang** [comment]
> 如果我们在普通的jar模块中引用ark plugin,然后将模块打成普通jar包，再在如果我们在普通的jar模块中引用ark plugin,然后将模块打成普通jar包，这个jar包里边的ark plugin也会被专门的arkplugin classloader加载对吧？
----
是的
