### ISSUE TITLE
biz包里有sofa-ark里相关的包

### ISSUE THREAD

**Issue by RongNanNan** [alipay/sofa-ark#130]
### Your question

biz包里为啥包含sofa-ark一些其他的包，我项目依赖的sofa-ark-springboot-starter的scope改成provided
打个包其实也是可以启动的并有隔离功能

**Comment by QilongZhang** [comment]
打入biz中的包都是你自行可控制的，sofa ark没有强制特殊包打入biz中。 sofa-ark-springboot-starter 是方便在ide中启动时，使用类隔离功能。如果是java -jar 启动，不需要依赖 sofa-ark-springboot-starter

**Comment by RongNanNan** [comment]
那示例项目里面建议把sofa-ark-springboot-starter的scope设置provided

**Comment by QilongZhang** [comment]
@RongNanNan  哪里，我改下。应该是建议设置成test.. 因为它是辅助在ide启动运行的。

**Comment by RongNanNan** [comment]
sofa-ark/sofa-ark-samples/sample-springboot-ark/pom.xml里的sofa-ark-springboot-starter
scope设置provided也不行设置test也不行，不然ide启动时就不会加载这个jar不会使用ark容器

**Comment by QilongZhang** [comment]
@RongNanNan  因为 sofa-ark-springboot-starter 有间接依赖吧，这不太好删除。Spring Boot 对待 spring-boot-devtools 的做法是在打包插件中写死
```java
exclude.setGroupId("org.springframework.boot");
exclude.setArtifactId("spring-boot-devtools");
```
这是因为 spring-boot-devtools 没有任何间接依赖，目前不是很容易做到把 sofa-ark-springboot-starter 及其间接依赖从biz包剔除。 

PS：biz 虽然是一个先对独立的包，但还是率属于 ark 框架的概念，如果打进sofa-ark-springboot-starter，ark 框架能保证没有比较坏的影响（能想到的是让biz包稍微变大），是否还是能接受的？

**Comment by RongNanNan** [comment]
间接依赖也还好不是很多，整体还是可以接受的

**Comment by QilongZhang** [comment]
@RongNanNan  嗯!
