### ISSUE TITLE
在springboot项目中，将外部ark-plugin（非maven引入）， 怎么导进来呢

### ISSUE THREAD

**Issue by luoluo001** [alipay/sofa-ark#131]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by QilongZhang** [comment]
可以参考 https://github.com/alipay/sofa-jarslink 。如果需要使用api的形式，会在下个版本提供。

**Comment by QilongZhang** [comment]
使用api 的形式单独issue 将在v0.6.0 完成 #135
