### ISSUE TITLE
首页中的介绍图画错了

### ISSUE THREAD

**Issue by sadwxqezc** [alipay/sofa-ark#132]
图里面的Graph Description，Biz Module是One-way Class Resolution，Plugin Module是Two-way Class Resolution?

**Comment by QilongZhang** [comment]
@sadwxqezc  没有画错， biz 只能单向加载 plugin 的导出类。 plugin 可以相互加载对方的导出类。

**Comment by sadwxqezc** [comment]
https://github.com/alipay/sofa-ark/blob/master/resource/SOFA-Ark-Framework.png
所以最下面的Graph Description不是画反了吗

**Comment by sadwxqezc** [comment]
https://github.com/alipay/sofa-ark/blob/master/resource/SOFA-Ark-Framework.png
所以最下面的Graph Description不是画反了吗

**Comment by sadwxqezc** [comment]
https://github.com/alipay/sofa-ark/blob/master/resource/SOFA-Ark-Framework.png
所以最下面的Graph Description不是画反了吗

**Comment by QilongZhang** [comment]
@sadwxqezc  没有画反， graph description 这是单纯的对符号描述，每个符号的描述都是独立的。

**Comment by sadwxqezc** [comment]
明白了，图有点误导性，哈哈
