### ISSUE TITLE
Provide api to operate biz.

### ISSUE THREAD

**Issue by QilongZhang** [alipay/sofa-ark#135]
Provide api to operate biz, such install, uninstall..

**Comment by Mr-onion** [comment]
是否能操作ark-plugin 而不是 biz

**Comment by QilongZhang** [comment]
> 是否能操作ark-plugin 而不是 biz

不可以

**Comment by Mr-onion** [comment]
谢谢回答，我还有三个问题期待帮忙解惑：
1. ark-plugin 能否通过api或者类似jarslink的方式动态的加载，以供biz调用，如果没有，是否有计划对此进行支持呢。biz层面的的动态加载有些重了，有时候可能只是需要通过类隔离和动态加载实现对某些小功能的动态扩展
2. 在biz中能否通过反射调用ark-plugin export的类
3. 在biz中能否通过plugin name和 接口名 调用plugin export出的对此接口的实现，如果可以怎么实现呢
