### ISSUE TITLE
sofa-ark无法加载被Spring增强过的export类

### ISSUE THREAD

**Issue by jiangyunpeng** [alipay/sofa-ark#145]
### Describe the bug
1. 类ToolkitAutoConfiguration 已经在插件中声明export。
2. 类ToolkitAutoConfiguration 被spring加载并增强为ToolkitAutoConfiguration$$EnhancerBySpringCGLIB$$ffaad2a0 

AbstractClasspathClassloader.resolveExportClass(name)方法如下
```
	protected Class<?> resolveExportClass(String name) {
		if (shouldFindExportedClass(name)) {
			ClassLoader importClassloader = classloaderService.findExportClassloader(name);
			if (importClassloader != null) {
				try {
					return importClassloader.loadClass(name);
				} catch (ClassNotFoundException e) {
					// ignore
				}
			}
		}
		return null;
	}
```
ClassloaderService.findExportClassloader()内部实现是一个Map，通过key-value匹配方式匹配，这样被动态增强的代码就无法被匹配到。

**Comment by QilongZhang** [comment]
@jiangyunpeng  经过代理增强的类没有考虑到，大概看了下常用的代理：
+ JDK 官方代理：com.sun.proxy.$com.sun.proxy.$Proxy + 数字
+ Cglib/Spring Cglib: 根据双$$判断
+ ByteBuddy: 默认情况下，$ByteBuddy$ 判定
+ 使用 Javassist、ByteBuddy可以自定义生成后的类全名

这些情况在特殊情况下都会遇到问题.

**Comment by QilongZhang** [comment]
针对该问题的解决方案参考 Equinox 框架处理，0.6.0 版本不再枚举导出包下的所有类，去除 key-value 的映射逻辑，按导出包名判断前缀。 例如用户导出包 `org.springframework.*`，不在对该包下的所有类进行扫描，统一在加载期间进行包名前缀判断，这样能解决spring 代理增强问题。

**Comment by johnyannj** [comment]
Cglib/Spring Cglib: 根据双$$判断 ===> 这个代理出来的类，会用spring上下文里的classloader define一个代理类。 导致代理类和被代理类会在不同的classloader下面。原本被代理类里引用的类在原classloader里可以，到新的classloader就不行了。

**Comment by QilongZhang** [comment]
> Cglib/Spring Cglib: 根据双$$判断 ===> 这个代理出来的类，会用spring上下文里的classloader define一个代理类。 导致代理类和被代理类会在不同的classloader下面。原本被代理类里引用的类在原classloader里可以，到新的classloader就不行了。

麻烦能否提供一个复现的 demo.

**Comment by johnyannj** [comment]
> 
> 
> > Cglib/Spring Cglib: 根据双$$判断 ===> 这个代理出来的类，会用spring上下文里的classloader define一个代理类。 导致代理类和被代理类会在不同的classloader下面。原本被代理类里引用的类在原classloader里可以，到新的classloader就不行了。
> 
> 麻烦能否提供一个复现的 demo.

好的 有时间提供下

**Comment by johnyannj** [comment]
我很难写一个合适的例子， 不过问题就是这个issue里描述的问题
https://github.com/spring-projects/spring-framework/issues/16241
