### ISSUE TITLE
优化IDE调试增加开发效率

### ISSUE THREAD

**Issue by iteaj** [alipay/sofa-ark#149]
### Your question
`        @Override
        public List<BizArchive> getBizArchives() throws Exception {
            List<URL> urlList = filterUrls(Constants.ARK_BIZ_MARK_ENTRY);

            List<BizArchive> bizArchives = new LinkedList<>();
            bizArchives.add(createDirectoryBizModuleArchive());

            for (URL url : urlList) {
                bizArchives.add(new JarBizArchive(new JarFileArchive(new File(url.getFile()))));
            }

            return bizArchives;
        }`
以上这段代码实现的功能是查找类路径下面的Biz包。以下两种情况：
1. 如果biz项目已经打包成Jar包则可以顺利加载这些Biz项目(这种情况适合项目发布)；
2. 如果biz项目还未打包成jar(在开发工具调试时)， 则只能加载根项目，代码如下：
` bizArchives.add(createDirectoryBizModuleArchive());`，其他的biz项目根本无法当成biz项目加载, 导致调试的时候不能用
### Your scenes

describe your use scenes (why need this feature)

### Your advice
开发工具加载的类路径为：jdk路径, maven的本地仓库路径，项目的目录路径。
1. 如果Biz已经发布到本地仓库， 这种情况下正常加载即可
2. 如果Biz还没发布到本地仓库， 这种情况可以使用如果方式加载：在编译目录下新增mark文件和manifest文件， 然后通过：createDirectoryBizModuleArchive()方式加载biz包
### Environment

- SOFAArk version: 0.5.2
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version: idea

**Comment by iteaj** [comment]
@QilongZhang sofa-ark-all这个Jar的源码是哪个git地址，方便后续可以对项目进行PR

**Comment by QilongZhang** [comment]
@iteaj  感谢，我们考虑出一个合适的解决方案。
另外请问下，如果是公司注册，能否再 https://github.com/alipay/sofa-ark/issues/152 提供你们的信息？

**Comment by iteaj** [comment]
> @iteaj 感谢，我们考虑出一个合适的解决方案。
> 另外请问下，如果是公司注册，能否再 #152 提供你们的信息？
抱歉， 我是属于个人开发爱好者。 想知道一下你们的解决方案会放到哪个版本，如果可以的话把新增的部分代码发给我一下， 我在本地构建一个（0.5.2）的ark容器， 方便我本地调试
首先，先感谢你们开源这么好的产品
其实， 现在在使用此框架开发一个开源产品(多web项目加载，一个web容器，运行多个web上下文)， 但是调试非常麻烦
最后，提个意见， 能否把ark容器独立出来，为容器设置一个单独的工作目录

**Comment by QilongZhang** [comment]
你说的单独工作目录是指啥？

另外我们也在开发类似的多web合并部署，在蚂蚁内部多web应用支持好久了，如果有兴趣也可以一起探讨。

**Comment by iteaj** [comment]
@QilongZhang 
1. 如果ark容器独立出来， 那么需要有地方存放容器和biz模块、插件以及配置文件。在容器启动的时候可以自动启动工作目录下的插件以及biz模块
2. 多web部署的方案很简单，  tocmat容器以及jetty容器本就支持多项目部署, 我只是简单的提供了spring boot的支持而已

**Comment by QilongZhang** [comment]
> @QilongZhang
> 
> 1. 如果ark容器独立出来， 那么需要有地方存放容器和biz模块、插件以及配置文件。在容器启动的时候可以自动启动工作目录下的插件以及biz模块
> 2. 我对多web的实现思路比较简单，  tocmat容器以及jetty容器本就支持多项目部署, 我只是简单的提供了spring boot的支持而已， 仅供参考

这走的还是传统的web容器模式，违背了单一整体 fatjar 启动方式。 sofaark 提供了api运行时动态安装卸载 biz, 不需要固定目录扫描。

**Comment by QilongZhang** [comment]
关于多 Biz 在 IDE 启动调试时， 目前的做法会启动 classpath 上的普通 biz 包以及将当前工程当成一个特殊的 DirectoryBiz，因为普通的 Biz 包是一个 fatjar，如果需要调试这个 Biz 包，需要通过远程调试代码。

**Comment by QilongZhang** [comment]
@iteaj  多web合并部署在0.6.0开始支持，可以看下是否你当时的设想。https://github.com/alipay/sofa-ark/issues/202
