### ISSUE TITLE
文档中描述的疑问

### ISSUE THREAD

**Issue by hqq2023623** [alipay/sofa-ark#150]
https://alipay.github.io/sofastack.github.io/docs/ark-biz.html
![clipboard](https://user-images.githubusercontent.com/6971152/49022095-063d3900-f1cf-11e8-9f70-96d3844aeafb.png)

我的理解是应该改成 打包发布Ark Biz包
这里说的是打成Ark包，那依赖的就是Ark包， 和本段的Ark容器支持多个Ark Biz包是不符合的

**Comment by QilongZhang** [comment]
感谢~ 文档描述错误，如你所说，是打成 ark biz 包

**Comment by QilongZhang** [comment]
@hqq2023623   已经fix了。 SOFAStack 官网文档在 http://www.sofastack.tech/sofa-boot/docs/sofa-ark-ark-biz
