### ISSUE TITLE
使用上的问题-ide如何识别plugin及plugin如何引用

### ISSUE THREAD

**Issue by wangwj** [alipay/sofa-ark#153]
### Your question
 写了一个测试demo有两个疑问
1.ide 识别的问题
看例子maven工程引入类似如下
 <dependency>
            <groupId>com.ultra.ark</groupId>
            <artifactId>ark-plugin-servicea</artifactId>
            <classifier>ark-plugin</classifier>
            <version>1.0</version>
        </dependency>
     <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-ark-springboot-starter</artifactId>
            <version>0.5.2</version>
        </dependency>
打出来的plugin，不是标准jar，ide识别不出来
2.如果plugin 相关依赖
和上述的方法一样吗

**Comment by QilongZhang** [comment]
不是标准的jar是什么意思？ plugin 是一个fatjar, 目录格式是ark容器负责识别的。

**Comment by wangwj** [comment]
我用的idea不能识别plugin的类

**Comment by QilongZhang** [comment]
> 我用的idea不能识别plugin的类

不理解你说的 idea 不识别是什么意思，能不能具体点描述？ 或者给出demo呢

**Comment by wangwj** [comment]
@QilongZhang ，sorry，就是发工具，比如eclipse，idea

**Comment by wangwj** [comment]
刚看到一个issue，说是引入provide 的jar，在0.5.2我看install的时候，这个没有install、还有就是deploy也没有把这个jar发不上去，如果是这样的话，插件应该生成两个jar,一个用来编译用的，一个是fatjar，并且都应该能install，deploy

**Comment by djsshu** [comment]
你好就是引入

**Comment by djsshu** [comment]
<dependency>
            <groupId>com.ucarinc.api</groupId>
            <artifactId>openAPI</artifactId>
            <classifier>ark-plugin</classifier>
            <version>200.1.200-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.ucarinc.api</groupId>
            <artifactId>openAPI</artifactId>
            <version>200.1.200-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

**Comment by djsshu** [comment]
<dependency>
            <groupId>com.ucarinc.api</groupId>
            <artifactId>openAPI</artifactId>
            <classifier>ark-plugin</classifier>
            <version>200.1.200-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.ucarinc.api</groupId>
            <artifactId>openAPI</artifactId>
            <version>200.1.200-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

**Comment by djsshu** [comment]
<dependency>
            <groupId>com.ucarinc.api</groupId>
            <artifactId>openAPI</artifactId>
            <classifier>ark-plugin</classifier>
            <version>200.1.200-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.ucarinc.api</groupId>
            <artifactId>openAPI</artifactId>
            <version>200.1.200-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>  在idea的spring cloud项目的pom里 引入这两个依赖，但是项目无法引入这个依赖里的类，找不到这个依赖里的类

**Comment by djsshu** [comment]
<dependency>
            <groupId>com.xxx.api</groupId>
            <artifactId>xxAPI</artifactId>
            <classifier>ark-plugin</classifier>
            <version>200.1.200-SNAPSHOT</version>
      </dependency>                                                                                                              
     <dependency>
        <groupId>com.xxx.api</groupId>
        <artifactId>xxAPI</artifactId>
        <version>200.1.200-SNAPSHOT</version>
        <scope>provided</scope>
    </dependency>  在idea的spring cloud项目的pom里 引入这两个依赖，但是项目无法引入这个依赖里的类，找不到这个依赖里的类,请问这个是什么原因？

**Comment by wangwj** [comment]
既然要隔离，为什么还要去依赖里边的库呢

**Comment by QilongZhang** [comment]
> 既然要隔离，为什么还要去依赖里边的库呢

应该只是为了编译通过

**Comment by QilongZhang** [comment]
> com.xxx.api xxAPI ark-plugin 200.1.200-SNAPSHOT com.xxx.api xxAPI 200.1.200-SNAPSHOT provided 在idea的spring cloud项目的pom里 引入这两个依赖，但是项目无法引入这个依赖里的类，找不到这个依赖里的类,请问这个是什么原因？

目前打包 plugin 的类是不会以 .class 形式打入，而是直接打入 lib/目录下面。因此引入依赖发现看不到包。  初衷是认为 plugin 中的类不会给biz直接使用，只是包含配置打包的 pom.xml 文件，最多包含 也只是包含PluginActivator。 建议将需要给biz直接使用的类，放在另一个模块中，然后 plugin 引入这个模块依赖。

**Comment by djsshu** [comment]
> > com.xxx.api xxAPI ark-plugin 200.1.200-SNAPSHOT com.xxx.api xxAPI 200.1.200-SNAPSHOT provided 在idea的spring cloud项目的pom里 引入这两个依赖，但是项目无法引入这个依赖里的类，找不到这个依赖里的类,请问这个是什么原因？
> 
> 目前打包 plugin 的类是不会以 .class 形式打入，而是直接打入 lib/目录下面。因此引入依赖发现看不到 plugin 中的类文件。 初衷是认为 plugin 中的类不会给biz直接使用，只是包含配置打包的 pom.xml 文件，最多包含 PluginActivator。 建议将需要给biz直接使用的类，放在另一个模块中，然后 plugin 引入这个模块依赖。

对是为了编译通过，如何让plugin引入这个模块依赖？

**Comment by QilongZhang** [comment]
> 对是为了编译通过，如何让plugin引入这个模块依赖？

麻烦暂时改下 plugin 代码分层，plugin 打包模块不包含直接让biz直接依赖的代码，而是放在单独一个模块中。

我稍后研究是否做下优化，之前也有同学提出来类似需求，plugin的类也会以class文件的形式打包。

**Comment by QilongZhang** [comment]
@djsshu  已经在 PR #200  中支持将 plugin 中的类以 class 文件打入

**Comment by djsshu** [comment]
@QilongZhang 你好，请问更新哪个包版本还是更新插件版本？插件版本我这边好像最新才到0.5.2

**Comment by QilongZhang** [comment]
> @QilongZhang 你好，请问更新哪个包版本还是更新插件版本？插件版本我这边好像最新才到0.5.2

已经合并到主干代码，使用 0.6.0-SNAPSHOT 版本即可。
