### ISSUE TITLE
ark-maven-plugin 如何将项目打包成 war 的形式运行在 tomcat 下呢

### ISSUE THREAD

**Issue by cngddflzw** [alipay/sofa-ark#164]
### Your question

ark 如何将一个普通的 spring mvc 项目打包成 war 的形式直接扔到 tomcat 下面去跑呢?

比如像 spring-boot-maven-plugin 打出来的 war 包那样

**Comment by QilongZhang** [comment]
@cngddflzw  ark 目前不支持 war 包的打包格式.
