### ISSUE TITLE
mvn package failed when sofa-ark-springboot-starter‘s version mismatch sofa-ark-maven-plugin

### ISSUE THREAD

**Issue by jiangyunpeng** [alipay/sofa-ark#175]
### 问题描述
当依赖的sofa-ark-springboot-starter和sofa-ark-maven-plugin版本不一致时，运行maven package 会报错：
```
[ERROR] Failed to execute goal com.alipay.sofa:sofa-ark-maven-plugin:0.5.0:repackage (default-cli) on project sample-ark: Execution default-cli of goal com.alipay.sofa:sofa-ark-maven-plugin:0.5.0:repackage failed: duplicate SOFAArk Container dependency -> [Help 1]
```
我们有这种场景，sofa-ark-maven-plugin的版本定义在parent中，很少会升级，但是sofa-ark-springboot-starter的版本升级比较频繁，所以会两边版本不一致。

### 测试代码

https://github.com/jiangyunpeng/ark-agent-demo

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ark-agent-demo</artifactId>
        <groupId>me.qlong.tech</groupId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>sample-ark</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-ark-springboot-starter</artifactId>
            <version>0.5.2</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.alipay.sofa</groupId>
                <artifactId>sofa-ark-maven-plugin</artifactId>
                <version>0.5.0</version>
                <executions>
                    <execution>
                        <id>default-cli</id>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```
### 错误信息

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.662 s
[INFO] Finished at: 2019-01-12T13:31:04+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.alipay.sofa:sofa-ark-maven-plugin:0.5.0:repackage (default-cli) on project sample-ark: Execution default-cli of goal com.alipay.sofa:sofa-ark-maven-plugin:0.5.0:repackage failed: duplicate SOFAArk Container dependency -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[1]    27056 exit 1     mvn package -Dmaven.test.skip=true

```

**Comment by QilongZhang** [comment]
在打包时，要求 ark 打包插件的版本和ark starter版本是一致，因此会报错，这是合理的。

对这个特性，会在 0.6.0 加个开关，默认强制一致。
```xml
<enforceVersion>false</enforceVersion>
```

**Comment by QilongZhang** [comment]
@jiangyunpeng  私下沟通，这个开关还是不加了，在 0.x 保持这个逻辑，因为在0.4.0打包插件中，是强制ark 容器也是在0.4.0+ 版本以上。等1.0 版本稳定之后，会参考 spring  boot 的做法，不对插件和容器版本做强一致检测。

**Comment by djsshu** [comment]
你好，pom做了如下的配置，加了shades后package就报错，没加shadespackage不会报错，请问是什么原因导致？
          

> 
          <plugin>
                <groupId>com.alipay.sofa</groupId>
                <artifactId>sofa-ark-plugin-maven-plugin</artifactId>
                <version>0.5.2</version>
                <executions>
                    <execution>
                        <id>default-cli</id>
                        <goals>
                            <goal>ark-plugin</goal>
                        </goals>
                        <configuration>
                            <exported>
                                
                                <packages>
                                    <package>com.xxx.baseModules.openAPI.*</package>
                                </packages>
                            </exported>
                            <outputDirectory>../target</outputDirectory>
                            <shades>
                                <shade>org.hibernate:hibernate-validator:4.3.1.Final</shade>
                                <shade>javax.validation:validation-api:1.0.0.GA</shade>
                            </shades>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

> 

package报错如下：
[ERROR] Failed to execute goal com.alipay.sofa:sofa-ark-plugin-maven-plugin:0.5.2:ark-plugin (default-cli) on project openApiArk: Execution default-cli of goal com.alipay.sofa:sofa-ark-plugin-maven-plugin:0.5.2:ark-plugin failed: 3 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command

**Comment by djsshu** [comment]
生成的ark-plugin里依赖了业务的jar包，但是ark-plugin插件被引用到spring boot项目后，编译时ark-plugin依赖的业务jar包里的类所引用的jar包还是会跟引用这个ark-plugin的spring boot项目里的jar包的版本冲突，还是会出现类冲突，无法达到编译时类也是隔离的请问这个要怎么处理？就是这两个jar包版本冲突了

> 

           <shade>org.hibernate:hibernate-validator:4.3.1.Final</shade>
            <shade>javax.validation:validation-api:1.0.0.GA</shade>
> 
我想让ark-plugin里的jar包在编译时不跟spring cloud项目里引用的这两个jar包冲突还是只用shade里指定的版本

**Comment by QilongZhang** [comment]
@djsshu  麻烦提问开新的 issue 提问，尽量不要在已经关闭的issue 和 pr 中提无关的问题。另外希望尽量能够提供简单的 demo 复现。
