### ISSUE TITLE
业务包不打biz格式而是放在某个lib目录，sofa容器是否支持加载

### ISSUE THREAD

**Issue by wczqll** [alipay/sofa-ark#196]
背景：工程名称为edge，依赖了三方库
打包（不使用sofa时的打包）：打包后copy-dependency，把edge.jar和依赖包放到lib目录下，然后用mvn的assembly package plugin，打包成一个可发布的zip包。zip包格式如下：
  ---bin/start.sh
  ---bin/stop.sh
  ---config/xxx.properties
  ---config/xxx.yaml
  ---lib/edge.jar
  ---lib/others.jar
现在我讲edge改造成sofa工程，打包出来是个fat jar，能否把容器单独打成一个包，然后让容器加载lib目录下的所有的业务包。

**Comment by QilongZhang** [comment]
> 能否把容器单独打成一个包，然后让容器加载lib目录下的所有的业务包

你说的容器是指 SOFAArk 吗？ 不支持 SOFAArk 单独打包，而且SOFAArk 容器加载的应用包需要打成 Biz 包格式，
