### ISSUE TITLE
支持多 Web 应用合并部署

### ISSUE THREAD

**Issue by QilongZhang** [alipay/sofa-ark#202]
SOFAArk  0.6.0  开始支持多 Web 应用合并部署，多 web 应用部署时，采用单 Host，多 context  模式。tomcat 的配置由宿主应用决定(大部分时候是端口)。web 应用在打包 biz 时，需要增加 `webContextPath` 打包配置：
```java
<configuration>
	<attach>true</attach>
    <webContextPath>/app</webContextPath>
</configuration>
```
默认为 `/`.

**Comment by welkinxu** [comment]
@QilongZhang 你好sofa-ark1.x支持[多个 Spring Boot Web 应用合并部署，是仅支持单host多个context path模式吗？
多hosts 多端口模式是支持的吗？
