### ISSUE TITLE
能否提供一个结合sofa-rpc的例子

### ISSUE THREAD

**Issue by huangyunbin** [alipay/sofa-ark#214]
1 只是看到结合springboot的例子
2 sofaboot中的sofaboot-sample-with-rpc例子没有使用到sofa-ark

所以能够提供一个sofa-ark结合sofa-rpc的例子。

ps：sofa-rpc-all具体是怎么作为一个插件呢？

**Comment by QilongZhang** [comment]
@huangyunbin  换个依赖方式，引入
```xml
<dependency>
    <artifactId>rpc-sofa-boot-plugin</artifactId>
    <groupId>com.alipay.sofa</groupId>
</dependency>
```
依赖行。打包配置参考  https://github.com/alipay/sofa-rpc-boot-projects/blob/master/sofa-boot-plugin/pom.xml
