### ISSUE TITLE
支持tomcat吗，tomcat怎么使用

### ISSUE THREAD

**Issue by huangyunbin** [alipay/sofa-ark#219]
项目是直接tomcat+servlet，请问这个要怎么做啊？

**Comment by QilongZhang** [comment]
是指war包的方式部署吗？ 可以详细描述下问题

**Comment by huangyunbin** [comment]
是的，就是普通的war包部署。因为是servlet项目，所以也找不到入口的main方法去加入sofa-ark的入口拦截方法。也没用到spring，所以这种情况要怎么使用sofa-ark啊。

**Comment by QilongZhang** [comment]
@huangyunbin  目前还没有计划非 Spring  的 War 包部署，正在开发 Spring  Boot 工程 War 包格式部署，建议迁移至 Spring Boot 的方式。

**Comment by huangyunbin** [comment]
如果是tomcat+spring的war包呢，我发现是tomcat是另外起了一个线程启动spring的，线程堆栈中是没有main方法的。这个是怎么解决的呢？

**Comment by QilongZhang** [comment]
> 如果是tomcat+spring的war包呢，我发现是tomcat是另外起了一个线程启动spring的，线程堆栈中是没有main方法的。这个是怎么解决的呢？

这个没有调研，理论上和 Spring Boot 类似，Spring Boot War 包入口在 org.springframework.boot.web.servlet.support.SpringBootServletInitializer#onStartup， 可以根据 tomcat 的扫描机制做一层 hook，可以关注 #215 ，会在 1.0.0 支持 Spring Boot War 包部署格式。也欢迎 PR 支持

**Comment by xingcici** [comment]
你好 这个问题后续有解决吗
