### ISSUE TITLE
IntrospectBizEndpoint类里命名的endpoint=bizState不符合springboot的要求启动报错

### ISSUE THREAD

**Issue by wgqazll** [alipay/sofa-ark#220]
### Environment

- SOFAArk version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by QilongZhang** [comment]
Spring Boot 2.0.6 版本之前不支持驼峰命令，2.0.6 及以上版本已经 Fix. 参考官方 issue https://github.com/spring-projects/spring-boot/issues/14773
