### ISSUE TITLE
把springboot项目嵌入进ssm项目是否可以使用sofa-ark实现？

### ISSUE THREAD

**Issue by challange** [alipay/sofa-ark#224]
我希望把一个springboot的web项目打包嵌入进ssm项目中，两个项目类加载上互不干扰，但是ssm项目中可以调用嵌入的springboot项目的接口，请问sofa-ark可以实现吗

**Comment by QilongZhang** [comment]
理论上是可以的，但是在 ssm 项目中配置 ark 打包插件，以及使用 runtime-sofa-boot-plugin 时，配置起来会比较麻烦。 

你们可以试下~

**Comment by challange** [comment]
谢谢，我去试试。
