### ISSUE TITLE
例子项目的sample-springboot-ark  都没用到sample-ark-plugin，是怎么来验证插件的？

### ISSUE THREAD

**Issue by huangyunbin** [alipay/sofa-ark#232]
我看到4月12号的提交把sample-ark-plugin去掉了，这个是为什么啊？
去掉之后怎么验证插件啊？

**Comment by QilongZhang** [comment]
https://github.com/alipay/sofa-ark/tree/master/sofa-ark-samples/sample-ark-plugin 
没有去掉吧，在这里。

**Comment by johnyannj** [comment]
同问， 也没看到sample-springboot-ark 引用了 sample-ark-plugin
