### ISSUE TITLE
ark插件带入依赖的问题

### ISSUE THREAD

**Issue by huangyunbin** [alipay/sofa-ark#233]
ark插件应该是个fatjar，插件的依赖对于使用者应该是完全透明的，现在是会跟着引入进来的。
需要使用者再maven依赖的地方exclusion掉吗，类似这样：
```
<exclusions>
    <exclusion>
      <groupId>*</groupId>
      <artifactId>*</artifactId>
    </exclusion>
  </exclusions>
```

**Comment by QilongZhang** [comment]
ark 插件本身设计就是可以带依赖的，因为不是所有的依赖都需要被打到fatjar中。 如果你不想传递，可以设置 maven 依赖 optional 为true.
