### ISSUE TITLE
Support ARK Plugin when maven ark-plugin in ` <dependencyManagement>`

### ISSUE THREAD

**Issue by guanchao-yang** [alipay/sofa-ark#24]
* Support 

```java
    <dependencyManagement>
            <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>runtime-sofa-boot-starter</artifactId>
            <classifier>ark-plugin</classifier>
            <version>1.0.1</version>
        </dependency>
    </dependencyManagement>
```

* If this function not supported,then using spring-boot-maven-plugin the Fat Jar will be larger and larger.Actually  spring-boot-maven-plugin don't care the ark-plugin dependency in classpath or not.

**Comment by QilongZhang** [comment]
@guanchao-yang  Considering that it's not a normal usage of maven dependency; As one of the by-products, it will make code unfriendly;  we have no plan to support this feature.
