### ISSUE TITLE
Rules check for import/export class/resource

### ISSUE THREAD

**Issue by straybirdzls** [alipay/sofa-ark#36]
Currently if one plugin export and import the same class/resource, some unexpected results will occur. We should figure out rules check for such scenarios.

And on OSGI, it will check whether import class is exported by some other bundle, if not ,then will get error as "missing contrains..." . When figure out rules, we should also take this into consideration.

Rules can be checked on build stage or on runtime stage or both.

**Comment by straybirdzls** [comment]
- rule 1: Class/Resource with the same name can not be exported and imported by one ark plugin at the same time. This rule can both be checked on compile phase and runtime phase
- rule2: Class import by one ark plugin must be exported by some ark plugins(at least one ark plugin).  For this rule, maybe we should introduce strong-dependency and weak-dependency or add a switch?

**Comment by straybirdzls** [comment]
Will use strong-dependency strategy as default and add switch to close the check.  For circular dependency , let's discuss offline

**Comment by QilongZhang** [comment]
ok

**Comment by straybirdzls** [comment]
- rule3: If higher level plugin relies on lower plugin's class on **startup** time , will get CNF , and the plugin need to handle such situation. It means only after one plugin startup , the classloader will be prepared.  If two plugins have the same priority, the result will be random which is not recommended

**Comment by QilongZhang** [comment]
Write some reason for which this feature would not be implemented in v0.3.0. @straybirdzls

**Comment by straybirdzls** [comment]
Actually I have already written the codes,  but after adding the rules, many of our test cases fail, I start to think whether the rules are too strict and even they are necessary. After some thinking and discussion with @QilongZhang , we think:
1. In our class  loading logic, after import search, we will continue to search  the local classpath, after these rules check, seems the logic is useless
2. Compare with OSGI, we want to keep our implement light and more "free-style"
3. The check logic is a little disgusting, especially when consider about import package/export package, because  for convenience we produce export.index on build time, and the check make us to check export-package again..

So , I move this issue out of 0.3.0 to stop "YY" some features on our own, but to see whether this is a common feature for real user case scenario.

Please let me know if any of you have any ideas, thank you😄
