### ISSUE TITLE
Fix case on windows env and figure out whether there is any way to do CI integration under windows env

### ISSUE THREAD

**Issue by straybirdzls** [alipay/sofa-ark#46]
Test under sofa-ark-springboot-starter module, for example: `ArkBootRunnerTest` will fail under windows env because of `RunnerHelper` for `prepareForTest.sh` 

And we can try to figure out whether there is any way  to do CI integration under windows env

**Comment by QilongZhang** [comment]
em... it looks ugly  to construct sofa-ark-all.jar via shell script. we should abstract a `DirectoryArchiver` to parse ark container - -

**Comment by straybirdzls** [comment]
Yeah, I agree with you. Let's do it !

**Comment by straybirdzls** [comment]
We can use https://github.com/marketplace/appveyor for windows ci
