### ISSUE TITLE
plugin依赖biz下的特定资源文件如何解决

### ISSUE THREAD

**Issue by RongNanNan** [alipay/sofa-ark#52]
如特定plugin依赖项目名称（配置到资源文件里）进行监控操作，而这个文件又不可能放到该插件里，或为每次使用该插件的项目开发一个单独的只用来提供这个资源的附属插件，有解决办法吗？看文档是biz单项依赖plugin的，但对于极端情况怎么解决

**Comment by QilongZhang** [comment]
我理解你说的核心问题是 plugin 如何加载 biz 的资源，这个问题还在内部讨论中，如果你有好的方案可以提出来，欢迎共建。另外最好陈述实际开发中，具体的这种场景。

**Comment by QilongZhang** [comment]
麻烦请关注 https://github.com/alipay/sofa-ark/issues/58 期待共建😜
