### ISSUE TITLE
Support telnet command to view ark plugin

### ISSUE THREAD

**Issue by JoeKerouac** [alipay/sofa-ark#79]
Support telnet command to view ark plugin.

The logic of the current telnet processing command is to get the `ArkCommandHandler` from `Ark Plugin`, so in order to support the telnet command to view the `Ark Plugin`, need to create an `ark-plugin` project to complete (or can also add to the `jarslink-plugin`).

**Comment by QilongZhang** [comment]
@JoeKerouac  you can provide a built-in implementation of `com.alipay.sofa.ark.spi.service.session.CommandProvider` in SOFAArk, it is unnecessary to create a single ark-plugin just for this feature. This implementation need support to check some details about ark-plugin during runtime. You can reference [Jarslink CommandProvider](https://github.com/alipay/sofa-jarslink/blob/master/sofa-jarslink-parent/integration/src/main/java/com/alipay/sofa/jarslink/integration/command/JSKCommandProvider.java)

**Comment by JoeKerouac** [comment]
Thx, I also read this, but according to the code in 
 [com.alipay.sofa.ark.container.session.handler.ArkCommandHandler](https://github.com/alipay/sofa-ark/blob/master/sofa-ark-parent/core-impl/container/src/main/java/com/alipay/sofa/ark/container/session/handler/ArkCommandHandler.java)  in the ARK project and the code in [com.alipay.sofa.jarslink.integration.activator.JarslinkActivator](https://github.com/alipay/sofa-jarslink/blob/master/sofa-jarslink-parent/integration/src/main/java/com/alipay/sofa/jarslink/integration/activator/JarslinkActivator.java) in the jarslink project, this function must be written in other plugins, otherwise it will be very troublesome (to register this CommandProvider to RegistryService, must to construct a fake Plugin, and if published by other Plugin it will be simple). I think this feature can be put in jarslink, and there is no need to create a separate Plugin project.

**Comment by JoeKerouac** [comment]
ok @QilongZhang

**Comment by QilongZhang** [comment]
### Plugin Information
#### Meta Info
+ PluginName/PluginVersion
+ Plugin Priority
+ Plugin Activator
+ Export/Import

#### Service Info
+ Plugin Service Publication
+ Plugin Service Reference

#### Detail Info
+ GAV （groupId, ArtifactId, Version）
+ Plugin URL
+ Class Path
+ Plugin ClassLoader

### Plugin Command
+ plugin
> list plugin name 

+ help plugin
> print plugin command tips

+ plugin -m pluginName  pluginName2 (support wildcard)
> view plugin meta info

+ plugin -s pluginName pluginName (support wildcard)
> view plugin service info

+ plugin -d pluginName pluginName2 (support wildcard)
> view plugin detail info 

-m -s -d can be combined to print multi type info. such as -ms -sd  or -m -s
