### ISSUE TITLE
您好,请问怎么通过类名来获取ark plugin类对象?

### ISSUE THREAD

**Issue by letmegog** [alipay/sofa-ark#82]
### Your question

我想在运行时通过类名来获取类对象,使用Class.forName()报错:
"com.alipay.sofa.ark.exception.ArkLoaderException [ArkBiz Loader] Startup In IDE:Mock version : can not load class: Hessian4Service"
请问应该怎么做呢?

**Comment by QilongZhang** [comment]
@letmegog  能提供下你的工程代码吗？

**Comment by letmegog** [comment]
谢谢您的帮助,代码如下:
[java-web-base.zip](https://github.com/alipay/sofa-ark/files/2261321/java-web-base.zip)
