### ISSUE TITLE
2.x 版本springboot的ApplicationStartedEvent事件含义发生变化，导致ide启动有问题

### ISSUE THREAD

**Issue by RongNanNan** [alipay/sofa-ark#84]
### Your question

使用2.x版本的springboot的项目，添加sofa ark的starter后，ide启动了服务2次

经查询监听的ApplicationStartedEvent事件在2.x版本的springboot事件含义发生变化，非启动前
需添加：SofaArkBootstrap.launch(args);

是否考虑支持？另sofa ark是否对springboot的版本有限制？

**Comment by QilongZhang** [comment]
@RongNanNan  sofa ark 不会对spring boot有限制， `ApplicationStartedEvent`事件在2.0发生了变更，我们将兼容。

**Comment by RongNanNan** [comment]
ApplicationStartingEvent 在1.5.0版本开始取代了ApplicationStartedEvent事件

**Comment by RongNanNan** [comment]
https://docs.spring.io/spring-boot/docs/1.5.0.RELEASE/reference/htmlsingle/
https://docs.spring.io/spring-boot/docs/1.4.7.RELEASE/reference/htmlsingle/

参考章节：Application events and listeners

**Comment by QilongZhang** [comment]
@RongNanNan  本周将会兼容该启动事件。不过如果合适，欢迎PR，烦请告知。
