### ISSUE TITLE
使用sofa ark的maven插件打的biz包含有scope为provided的jar

### ISSUE THREAD

**Issue by RongNanNan** [alipay/sofa-ark#85]
ark-biz包里含有maven scope为provided的jar

- SOFAArk version: 0.2.0、 0.4.0
- JVM version  1.7
- Maven version: 3.3.9

**Comment by QilongZhang** [comment]
@RongNanNan  这是我们的 BUG， 打包 ark plugin 插件包是不会打入 provided 包，但是在打包 Ark  包是有问题，会额外打入 provided 的包。我们将尽快修复。

**Comment by QilongZhang** [comment]
![image](https://user-images.githubusercontent.com/8833026/43826111-16f9d016-9b29-11e8-9cfe-bced06780146.png)

我看了下代码，在 `com.alipay.sofa.ark.boot.mojo.ArtifactsLibraries` 这个类中移除 `Provided` 即可。 @RongNanNan  有没有兴趣提 PR 哈~

**Comment by QilongZhang** [comment]
@RongNanNan  已fix
