### ISSUE TITLE
在0.4.1-SNAPSHOT版本中provided的包的依赖还会打包到biz的lib中

### ISSUE THREAD

**Issue by letmegog** [alipay/sofa-ark#93]
### Your question

在0.4.1-SNAPSHOT版本中provided的包不会打到biz的lib中,但是这个包的依赖还会打到biz的lib中.这个正常吗?这些依赖包存在冲突是要手动排除吗?

### Environment

- SOFAArk version:0.4.1-SNAPSHOT
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):windows10
- Maven version:3.5
- IDE version:eclipse

**Comment by QilongZhang** [comment]
@letmegog  你好，从测试和代码分析看，应该不会存在你说的这种情况。能否提供下你那边的测试工程？

**Comment by letmegog** [comment]
@QilongZhang 你好，我在插件中引入了guava，打包时guava被打到了lib中.
[ark-demo.zip](https://github.com/alipay/sofa-ark/files/2280131/ark-demo.zip)

**Comment by QilongZhang** [comment]
@letmegog   是应该要被打进去的，有什么疑问吗？

**Comment by letmegog** [comment]
@QilongZhang provided包的依赖可能会有冲突啊,比如log4j-over-slf4j和slf4j-log4j12不能同时出现在classpath下.

**Comment by QilongZhang** [comment]
@letmegog  provided 的包不会打进去，你工程里的guava没有设置scope成provided

**Comment by letmegog** [comment]
@QilongZhang guava是插件的依赖,被provided标记的插件确实没有打到biz的lib中,但我理解这个被provided标记的插件的依赖也不应该被打到lib中.因为这可能引起冲突.

**Comment by QilongZhang** [comment]
@letmegog  理解错意思，这个问题已经别fix了 #88
