### ISSUE TITLE
sofa-ark-plugin-maven-plugin中标签shades的目的是什么

### ISSUE THREAD

**Issue by chixuan777** [alipay/sofa-ark#94]
### Your question

发现sofa-ark-plugin-maven-plugin中有标签shades

### Your scenes

plugin之间出现包依赖

### Your advice
发现和excludes作用一样，可以把不必要的jar中fatjar剥离出
并且plugin还可以直接使用这个jar中的类

我的问题是
1，使用的是其他plugin中的jar还是biz中import的jar，如果是其他plugin的jar，优先级是什么呢
2，如果其他插件已经把一个类export了，但是当亲plugin没有import会发生什么事情？是使用已经export的类还是自己用当前classload重新load个？

### Environment

- SOFAArk version:
- JVM version (1.8.0_71):
- OS version (MINGW64_NT-10.0 ):
- Maven version: 3.5.3
- IDE version:NA

**Comment by RobertoHuang** [comment]
plugin 中的lib目录包含的jar无法被应用直接使用，除非plugin将相应的类导出

我测试了一下 发现plugin中的lib也是可以正常被应用使用的呀 不太明白shades具体作用是干嘛
