### ISSUE TITLE
SOFAArk 启动期间 YGC 优化

### ISSUE THREAD

**Issue by straybirdzls** [alipay/sofa-ark#95]
写了个 SOFABoot 的工程，在没有使用 SOFAArk 之前，GC 次数为 6 次；在 使用之后(SOFAArk + rpc plugin)，启动期间 YGC 上升到 12～13 次

**Comment by QilongZhang** [comment]
![image](https://user-images.githubusercontent.com/8833026/44302598-cf00f580-a35e-11e8-8a09-59385fb04c0d.png)

![image](https://user-images.githubusercontent.com/8833026/44303615-ca950680-a377-11e8-9816-cc0c13824ed0.png)

![image](https://user-images.githubusercontent.com/8833026/44303617-da144f80-a377-11e8-915d-69df5d7faae9.png)

使用 JProfile 分析内存 dump 来看，上面三个图反应的是内存分配热点也是主要的改进点，可以看到集中在 Handler 方法的处理上，这个类主要用于 Jar 包 的解析，理论上 ark plugin 越多，启动期 YGC 会越频繁。
